orangecontrib/single_cell/tests/test_owlouvain.py, orangecontrib/single_cell/widgets/owlouvainclustering.py
Fixes #107 
Louvain runs clustering on any data change.
Louvain runs clustering only when X changes, since it does not use Y or metas for clustering.
Also a bit of cleanup.
=> [FIX] Louvain: Do not re-cluster on same data

requirements.txt
For https://github.com/biolab/orange3-single-cell/pull/125 to work, we introduced changes to OWDataSets in orange3 (https://github.com/biolab/orange3/pull/2950) which were included in release 3.12.0
Also, bump version for orange3-bioinformatics add-on.
=> requirements: bump bioinformatics version, specify orange3 version

orangecontrib/single_cell/preprocess/scbnorm.py, orangecontrib/single_cell/tests/preprocess/test_scbnorm.py, orangecontrib/single_cell/widgets/ownormalization.py
Speed-up computation of scores for batch variables by computing correlations in a matrix form.
Refactor and add test.
=> Speed-up computation of scores for batch variables

orangecontrib/single_cell/tests/test_owmarkergenes.py, orangecontrib/single_cell/widgets/owmarkergenes.py
Implements #137 
After TableModel is created change the column background RGB value.
Create new context handler, so widget remembers row selection based on selected group.
=> [WIP] owmarkergenes: change color of domain columns, add row selection setting

orangecontrib/single_cell/widgets/owmarkergenes.py
Missing values in Orange data table are displayed as "?". In case of this widget the missing values should be displayed as empty cells.
Display "" instead of "?".
=> OWMarkerGenes: Show empty cell instead of '?'

orangecontrib/single_cell/preprocess/clusteranalysis.py
The Cluster Analysis widget did not appear in a clean install, because it crashed when importing matplotlib in preprocess/clusteranalysis.py (matplotlib is not in requirements).
I moved the matplotlib import into the draw_pyplot function for now. Someone (@GolobicBogdan @jurijsteblaj ?) should take another look and see if and where we need this functionality.
=> [FIX] clusteranalysis.py: Fix imports

setup.py
Package data files (.tab, .tab.gz) in addition to *.ows.
=> [FIX] setup.py: Include data used in tutorials

orangecontrib/single_cell/widgets/owscdatasets.py
Widget did not annotate the output table properly. Gene id attribute was missing.
Add GENE_ID_ATTRIBUTE to the table attributes.
=> [FIX] owscdatasets: add missing GENE_ID_ATTRIBUTE

installer/macos/sign-app.sh
When multiple Developer ID certificates are installed, macOs bundles are not signed
Use a more specific certificate name, set it up in one place
=> refactor out certificate name

orangecontrib/single_cell/widgets/owloaddata.py, orangecontrib/single_cell/widgets/owmultisample.py
Since the Multi Sample widget can just as well be used to load one data set and incorporates the Load Data widget, having both is redundant.
The original Load Data widget is removed and Multi Sample renamed to Load Data.
=> Multi Sample -> Load Data

orangecontrib/single_cell/widgets/owmultisample.py
The select_item() function did not set the current item, just the selection. So _update_view_cells_genes() sometimes updated the wrong row.
To test: add a file, add another file, change Input Data Structure, values are overwritten in the first row instead of the second.
Set the currentIndex and do the selection instead of just selecting.
=> [FIX] owmultisample: Fix current item selection

orangecontrib/single_cell/tests/test_owmultisample.py, orangecontrib/single_cell/widgets/owmultisample.py
The widget did not save list of files into settings until data was loaded. 
List of files is saved into settings when the widget is deleted.
=> OWMultiSamples: Fix saving settings

orangecontrib/single_cell/widgets/owmarkergenes.py
Gene Marker data set had a strange name of the data table that would then show in widgets like Cluster Analysis.
Widget now sets the data table name to "Marker Genes".
=> [ENH] Gene Markers: sets the name of the output file

orangecontrib/single_cell/widgets/owaligndatasets.py, orangecontrib/single_cell/widgets/owbatchnorm.py, orangecontrib/single_cell/widgets/owdotmatrix.py, orangecontrib/single_cell/widgets/owfilter.py, orangecontrib/single_cell/widgets/owloaddata.py, orangecontrib/single_cell/widgets/owlouvainclustering.py, orangecontrib/single_cell/widgets/owmarkergenes.py, orangecontrib/single_cell/widgets/owscorecells.py, orangecontrib/single_cell/widgets/owscoregenes.py, orangecontrib/single_cell/widgets/owscpreprocess.py, orangecontrib/single_cell/widgets/owtsne.py
Redefines the order of the widgets in single cell add-on:
110 Load Data
150 Single Cell Data Sets
170 Marker Genes
210 Filter
220 Single Cell Preprocess
230	Batch Effect Removal
240 Align Datasets
310 Score Genes
320 Score Cells
410 Dot Matrix
910 Louvain Clustering
920 t-SNE
=> Redefine the order of the widgets

orangecontrib/single_cell/widgets/owloaddata.py, orangecontrib/single_cell/widgets/owmultisample.py
Load Data widget is now incorporated inside OWMultiSample so the priority change should be made there. OWLoadData should have an empty name to avoid both being visible.
=> Load Data: Revert name change

orangecontrib/single_cell/preprocess/cca.py
CCA did not support sparse matrices.
The only problematic part was that scipy doesn't have any direct way of computing standard deviation. This can easily be fixed through our `statistics.utils` module.
Depends on https://github.com/biolab/orange3/pull/3218.
=> CCA: Add sparse support

orangecontrib/single_cell/tests/preprocess/test_scpreprocess.py
Test failed with new version of scipy (1.1.0), because bin limits are treated differently.
=> [FIX] TestSelectMostVariableGene: fix failing test

orangecontrib/single_cell/widgets/owdotmatrix.py
Fixes #308 
Removed the entire `send_report` function which also removes the report button. The function never did anything useful and was just copied from another widget.
=> [FIX] OWDotMatrix: Removing reports and report button

orangecontrib/single_cell/widgets/owtsne.py
Once https://github.com/biolab/orange3/pull/3192 is merged, the tSNE widget here will no longer work due to the API change.
Should not be merged until https://github.com/biolab/orange3/pull/3192.
tSNE widget now works. I've removed the MulticoreTSNE code as well since the current implementation also implements Barnes-hut and is about as fast as MulticoreTSNE.
I've set the step size to 50 (chosen for no reason in particular), so the visualization is updated every 50 iterations. This is primarily done so the optimization can be stopped in between, otherwise one would have to wait until all iterations finished before the widget became responsive again.
One thing to note is the early exaggeration phase. The previous version was limited in the sense that the number of early exaggeration …
=> tSNE: Update to use new implementation

orangecontrib/single_cell/widgets/owscorecells.py
The widget always output None (on every received input) before outputting data.
=> [FIX] Score Cells: Do not output None if data exists

orangecontrib/single_cell/tests/test_load_data.py, orangecontrib/single_cell/tests/test_owloaddata.py, orangecontrib/single_cell/widgets/load_data.py
Load Data widget is slow when opening big excel files.
Beside that, most Excel files have at least one header row, so default number of header rows should be 1.
- xlrd is used (instead of pandas) to get number of rows and columns
- set default number of header rows and files to 1
=>  ExcelLoader: Speedup and enhancement

orangecontrib/single_cell/widgets/owdotmatrix.py
#309 
There was an error when user tried to change aggregation and there were no discrete variables in data. Now user is warned that there is no discrete variable and the widget acts as if there is no data on input.
=> [FIX] OWDotMatrix: Fixed errors which occur when no discrete variables

orangecontrib/single_cell/widgets/owscdatasets.py
We have added support for HTTPS on domain datasets.biolab.si. Certificates are auto-renewed by Cloudflare, no more letsencrypt scripts. The datasets can be cached on Cloudflare.
This PR relies on: https://github.com/biolab/orange3/pull/3412
=> Switch index url for Single Cell Datasets widget.

orangecontrib/single_cell/tests/test_owmultisample.py
Changes minimum allowed size for Load Data widget for exceptional reasons.
=> Modify minimum allowed size for Load Data widget

orangecontrib/single_cell/widgets/owdotmatrix.py
Tooltips don't match the row and column labels after row/column clustering.
Apply permutation for tooltips in the same way as for actual values.
=> [FIX] DotMatrix: Fix tooltips

orangecontrib/single_cell/widgets/contingency_table.py
Fixes #303 
This solution here is quite ugly. I don't know how to fix this properly.
If we input the iris dataset, the longest of the labels at the top has a size hint of (29, 98) after calling `self.resizeRowToContents(1)`. But if `self.horizontalHeader().setDefaultSectionSize(self.cell_size)` is called before that (the problem can occur at the next call of this method) with value 30, the size hint will be (46, 73). The other two labels have shorter and wider size hints as well. The delegate used is `CircleItemDelegate`, which uses methods from `gui.VerticalItemDelegate` for those labels.
The current fix stores the default `self.horizontalHeader().defaultSectionSize()`, which seems to be 100, and applies it before the call to `self.resizeRowToContents(1)`. After that it sets the value …
=> [FIX] ContingencyTable: Fix for labels getting cut off in circle mode

installer/windows/build-conda-installer.sh, installer/windows/condainstall.bat, installer/windows/sitecustomize.py
Installed shortcuts, registry commands,... use installed anaconda python distribution without activation, but:
`conda install --prefix ./test python=3.7.3 numpy`
then without activating the test env
`.\test\python.exe -c "import numpy" fails with a `ImportErorr: DLL load failed...`
Do the equivalent of https://github.com/AnacondaRecipes/python-feedstock/commit/d6830a4afa9aed2ee296accdc6e3d2d3996074ce#diff-d4e4e88c0c4b6c1e582c1d0fa9543940
(which is no longer applied to latest anaconda python 3.7.3)
This does not fix the fact that we use conda in a way that runs counter to their design.
=> [FIX] Conda Installer: Restore compatibility with latest anaconda python

orangecontrib/single_cell/widgets/owfilter.py
[Fix an "AttributeError: 'NoneType' object has no attribute 'hide'"](https://travis-ci.org/biolab/orange3-single-cell/jobs/553635199#L1283)
Clear the scene in onDeleteWidget
=> [FIX] owfilter: Clear the scene in onDeleteWidget

orangecontrib/single_cell/widgets/owaligndatasets.py
Final two checkboxes are not aligned.
Wrap 'Dynamic time warping' in its own box as 'Quantile normalization' is already pre-wrapped in a box, which causes misalignment.
Also remove unused imports.
=> [FIX] Align Datasets: align checkboxes

orangecontrib/single_cell/widgets/owaligndatasets.py
Widget chrashes when receives data with only one data source
Now it shows an error when it happens.
=> [FIX] OWAlignDatasts: Show error when only one data source

orangecontrib/single_cell/tests/test_owaligndatasets.py, orangecontrib/single_cell/widgets/owaligndatasets.py
The widget does not use a separate thread for computation. When data are connected to the widget it selects fist discrete attribute and uses it as a source ID. If it is an attribute with several different values computation takes long and freezes Orange.
If we find the `Source ID` variable in data we assume it is dataset source id, so we set it as a Source ID attribute.
=> OWAlignDatasets: Set Source ID as a source ID parameter by default

orangecontrib/single_cell/preprocess/scpreprocess.py, orangecontrib/single_cell/tests/test_owdropout.py, orangecontrib/single_cell/widgets/owdropout.py
Optimize implementation of #348
Due to simplicity the graph was reploted on any parameter change / curve move / input markers change.
Now the graph retains its items, only the curve is moved by re-setting its coordinates.
=> Dropout: Speedup reploting

doc/widgets.json
New website requires widgets.json to show docs.
Add widgets.json.
File generated with:
`python ~/orange/orange-hugo/scripts/create_widget_catalog.py  --categories "Single Cell" --doc .`
The script, however, doesn't work with index.md, so I temporarily changed it to index.rst and it worked. We should find a better solution though (try/except?).
Dot Matrix was not matched with corresponding documentation, so I added it manually.
Dropout Gene Selection missing documentation.
=> Add widgets.json

orangecontrib/single_cell/widgets/load_data.py
DiscreteVariable.values in Orange is now a tuple.
Removed append and added concatenating tuples.
=> DiscreteVariable.values is a tuple

orangecontrib/single_cell/preprocess/scpreprocess.py, orangecontrib/single_cell/tests/preprocess/test_scpreprocess.py
[`single_cell.preprocess.scpreprocess`](https://github.com/biolab/orange3-single-cell/blob/master/orangecontrib/single_cell/preprocess/scpreprocess.py) does not support sparse data.
Add sparse support to preprocessors. Does not include [`single_cell.preprocess.scpreprocess.Standardize`](https://github.com/biolab/orange3-single-cell/blob/master/orangecontrib/single_cell/preprocess/scpreprocess.py#L107-L118), as some thought will have to be put into how to handle this elegantly.
=> ScPreprocess: Add sparse support

orangecontrib/single_cell/tests/test_owdatasets.py, orangecontrib/single_cell/tests/test_owfilter.py, orangecontrib/single_cell/tests/test_owloaddata.py, orangecontrib/single_cell/widgets/load_data.py, orangecontrib/single_cell/widgets/owfilter.py, orangecontrib/single_cell/widgets/owloaddata.py, orangecontrib/single_cell/widgets/owscdatasets.py, setup.py
This PR solves several issues in the addon:
- Addon now support Pandas version >=1.1
- SC Datasets is updated to a newer version of the Orange Dataset widget
- Updated deprecated `len(domain)` in filter
- `_upate_summary` function is now function in the `orangewidget.sinals` which interfered with `_upate_summary`  in Filter widget. Function in Filter widget is temporarily renamed. This functionality could be later changed or removed when default summaries will be available by Orange.
-
=> Several fixes

orangecontrib/single_cell/preprocess/scpreprocess.py, orangecontrib/single_cell/widgets/owscpreprocess.py
Besides CPM or counts per million, the single-cell literature also mentions CP10K or counts per 10000 as a normalization method. The difference in the method is noticeable after logarithmizing the data and in later downstream analysis.
Added a few lines of code to NormalizeSamples in scpreprocess.py and NormalizeEditor in owspreprocess.py.
=> Add counts per 10k as a normalization option

.github/workflows/release.yml
This PR introduces a reusable workflow that allows release automatically. It is reusable -- we do not need to update every repository separately. Instruction on how to use it is in [Orange wiki in Automated release section](https://github.com/biolab/orange3/wiki/Preparing-an-Add-on-release#automated-release).
=> [CI] Workflow for automated release

orangecontrib/single_cell/widgets/load_data.py, orangecontrib/single_cell/widgets/owloaddata.py
Fixes #389.
This pull request resolves several issues. First, it fixes a bug that prevented manual addition of cell and gene annotations. Additionally, files named 'genes.tsv', 'features.tsv', 'genes.tsv.gz', and 'features.tsv.gz' for genes, as well as 'barcodes.tsv' and 'barcodes.tsv.gz' for barcodes, are now automatically recognized and added.
Furthermore, it addresses a bug where source names were not correctly assigned. Previously, when loading two scRNA matrices with different source names, both sources would incorrectly inherit the source name of the first one. This issue has now been fixed.
=> [FIX] LoadData - Manually add gene and cell annotations, correct Source name

doc/index.rst, doc/widgets.json, orangecontrib/single_cell/widgets/load_data.py, orangecontrib/single_cell/widgets/owloaddata.py
This pull request resolves several issues. First, it fixes a bug that prevented manual addition of cell and gene annotations. Additionally, files named 'genes.tsv', 'features.tsv', 'genes.tsv.gz', and 'features.tsv.gz' for genes, as well as 'barcodes.tsv' and 'barcodes.tsv.gz' for barcodes, are now automatically recognized and added.
Furthermore, it addresses a bug where source names were not correctly assigned. Previously, when loading two scRNA matrices with different source names, both sources would incorrectly inherit the source name of the first one. This issue has now been fixed.
=> [FIX] LoadData - Bugs with gene and cell annotations

orangecontrib/single_cell/widgets/load_data.py, orangecontrib/single_cell/widgets/owmultisample.py
The widget crashes with `ValueError: Duplicate values in DiscreteVariable` when opening multiple files with the same name.
Make source names unique before creating the output table.
=> [FIX] Multi Sample: Add postfix to non-unique names
