biolab/orange3-single-cell

- orangecontrib/single_cell/widgets/owloaddata.py
Implements gh-117
(supersedes #122 - because the repositories are no longer linked and I cannot update the PR from there)
Add support for reading 10x gene-barcode matrices in .mtx format
> [ENH] owloaddata: Add support for 10x gene-barcode matrices (.mtx format)

- orangecontrib/single_cell/widgets/owfilter.py
> owfilter: exclude 0 when filtering data values

- orangecontrib/single_cell/widgets/owfilter.py
Filter cells by total counts across all genes (library size) seems to also be frequently used.
(replaces gh-54)
Add filter by total counts.
> [ENH] Filter: Add filter by total counts

- CHANGELOG.md
Change log was too abbreviated, needed cosmetic changes. The goal is to show change log with new installation of scOrange, hence it needs to be sufficiently descriptive.
Reworded the items in change log and changed titles.
> [FIX] Changelog in readable format

- orangecontrib/single_cell/widgets/owscdatasets.py
- requirements.txt
https://github.com/biolab/orange3-single-cell/issues/121
Depends on https://github.com/biolab/orange3/pull/2950
> OWscDataSets: include information about an organism in data sets

- orangecontrib/single_cell/preprocess/scbnorm.py
- orangecontrib/single_cell/tests/preprocess/test_scbnorm.py
- orangecontrib/single_cell/widgets/ownormalization.py
Implements batch normalization, issue #123 .
> Batch normalization class and widget

- orangecontrib/single_cell/preprocess/scnormalize.py
- orangecontrib/single_cell/tests/preprocess/test_scnormalize.py
> [FIX] Normalize: Transform only numeric variables

- orangecontrib/single_cell/widgets/owscdatasets.py
Fixes #138.
Depends on https://github.com/biolab/datasets/pull/56
> [FIX] owscdatasets: use information on number of genes (from .info files)

- orangecontrib/single_cell/widgets/owmarkergenes.py
Make Reference column clickable and open belonging Url.
> OWMarkerGenes: Open URL by clicking Reference

- orangecontrib/single_cell/widgets/owmarkergenes.py
> [REF] add data attributes to the output, override ColorForRole variable

- orangecontrib/single_cell/preprocess/clusteranalysis.py
resolves #160 
Fixes and enhancements have been implemented that are pointed out in the issue #160.
> [ENH] Cluster analysis backend

- orangecontrib/single_cell/widgets/owscorecells.py
- requirements.txt
resolves #132 
resolves #148 
WIdget now works with ids provided from [NCBI](https://www.ncbi.nlm.nih.gov/gene) database.
Input data table must have the attribute (Gene ID) set for each of the variables (genes).
Variables with no 'gene_id' attribute are ignored in the matching process.
TODO:
- _Update example datasets in datasets.orange.biolab.si/sc/ with NCBI ids._ https://github.com/biolab/datasets/pull/57
- _Update marker genes with NCBI ids._
> [ENH] owscorecells: match genes by gene_id attribute

- orangecontrib/single_cell/preprocess/clusteranalysis.py
- orangecontrib/single_cell/widgets/owclusteranalysis.py
Fixes #172 
Calculation which happens after data or option change is now executed in threads.
Also fixed reasons for crashes in #172.
> OWClusterAnalysis: Threads & progress bar and #172 fix.

- orangecontrib/single_cell/preprocess/clusteranalysis.py
resolves #169 
resolves #167
Fixed calculation of over-expression, now it matches the results of the Differential expression widget. Added an option to bicluster the resulting matrix or leave it unshuffled. Also added caching and callback for reporting progress.
> clusteranalysis.py: fixes for issues #167 and #169

- orangecontrib/single_cell/widgets/owclusteranalysis.py
Resolves #170
Added the checkbox requested in #170.
Also disabled differential expression options when a list of genes is provided.
> Checkbox for toggling of biclustering

- orangecontrib/single_cell/preprocess/clusteranalysis.py
- orangecontrib/single_cell/widgets/owclusteranalysis.py
- orangecontrib/single_cell/widgets/owmarkergenes.py
Resolves #168 
OWClusterAnalysis: Detects gene list data. Fixed limiting to 50.
ClusteraAnalysis: enriched_genes now works on gene IDs and not names.
OWMarkerGenes: Marks where its gene ID column is.
> OWClusterAnalysis: Reads where gene IDs are located for "Genes" input.

- orangecontrib/single_cell/preprocess/scnormalize.py
- orangecontrib/single_cell/tests/preprocess/test_scnormalize.py
- orangecontrib/single_cell/widgets/ownormalization.py
> Add binarization to the Normalize widget.

- orangecontrib/single_cell/preprocess/clusteranalysis.py
- orangecontrib/single_cell/widgets/owclusteranalysis.py
- orangecontrib/single_cell/widgets/owmarkergenes.py
- orangecontrib/single_cell/widgets/owscorecells.py
> [ENH] Handle annotated tables in single cell widgets

- orangecontrib/single_cell/widgets/owscorecells.py
Fixes #190 
Remove gene column selection. Use data attributes to identify organism and gene id location.
> [ENH] Score Cells: use data attributes, simplify user interface

- orangecontrib/single_cell/widgets/owclusteranalysis.py
Fixed context settings.
Changed input and output code to conform to prescribed form.
> [FIX] OWClusterAnalysis: Context settings

- orangecontrib/single_cell/widgets/owscoregenes.py
> [FIX] owscoregenes: annotate table on scores output

- orangecontrib/single_cell/widgets/contingency_table.py
> OWClusterAnalysis: Key shortcut to select all

- orangecontrib/single_cell/widgets/owtsne.py
Change Selected Data output to match that of Scatter Plot by adding a meta column ("Group") with group identifiers.
> [FIX] t-SNE: Add Group column to Selected Data output

- orangecontrib/single_cell/widgets/owscorecells.py
#153
This is a first try at #153 adding the option to change from max to mean and median.
Before merging we should try and evaluate some additional (more advanced?) approaches and decide what to include.
> [ENH] Score Cells: Add multiple aggregation choices

- orangecontrib/single_cell/widgets/owtsne.py
Even if only a meta variable changed in the data, t-sne was rerun.
This happened because before receiving the new/similar data, the input was first cleared which invalidated t-sne.
Do the check in handleNewSignals, which is called once instead of in set_data which was called twice (first with None, then with actual data)
> [FIX] owtsne: Fix checking of input data to avoid recomputation

- orangecontrib/single_cell/widgets/load_data.py
- orangecontrib/single_cell/widgets/owloaddata.py
- orangecontrib/single_cell/widgets/owmultisample.py
Source name -> Source Name, categorical
Enable “Sample Data”
When adding data, checkbox is checked by default
> LoadData: Fixups

- orangecontrib/single_cell/launcher/welcome.py
- requirements.txt
The multi window/workflow editing in Orange 3.14.0 broke the SCLauncher
Update the welcome dialog to work with Orange 3.14
> [FIX] SCLauncher: Fix welcome screen monkey patch to work with Orange 3.14

- orangecontrib/single_cell/widgets/contingency_table.py
- orangecontrib/single_cell/widgets/owclusteranalysis.py
Resolves #205 
Adds zoom levels to Cluster Analysis widget (the one which will be renamed to Dot Matrix or something similar).
> OWClusterAnalysis: Dot matrix zoom

- doc/index.rst
Remove the toc entries for previous widgets that have been removed/replaced.
> [DOC] Remove dead doc links

- orangecontrib/single_cell/tests/test_owfilter.py
- orangecontrib/single_cell/widgets/owfilter.py
Ref gh-56
Add option to display the distribution in log scale.
> [ENH] owfilter: Display plot on a log scale

- orangecontrib/single_cell/preprocess/alignment.py
- orangecontrib/single_cell/tests/test_owmda.py
- orangecontrib/single_cell/widgets/owmda.py
Widget implementation for issue #228.
Prototype of a widget for Seurat Multiple data alignment. Design was taken from #228.
> Widget for Seurat Multi-dataset alignment

- orangecontrib/single_cell/widgets/owscpreprocess.py
Widget description was incorrect.
> OWscPreprocess: Change widget description

- requirements.txt
> requirements: fix sklearn -> scikit-learn

- orangecontrib/single_cell/tests/test_owbatchnorm.py
- orangecontrib/single_cell/widgets/owbatchnorm.py
> OWBatchEffectRemoval: New widget

- orangecontrib/single_cell/widgets/owloaddata.py
> OWLoadData: Change file format label and error message

- orangecontrib/single_cell/widgets/owbatchnorm.py
> OWBatchNorm: Display only primitive meta attributes

- orangecontrib/single_cell/widgets/owbatchnorm.py
> [FIX] OWBatchNorm: Translate (schema) saved variables to existing ones

- orangecontrib/single_cell/tests/test_owmarkergenes.py
- orangecontrib/single_cell/widgets/owmarkergenes.py
Fixes #273 
Also fixed: Taxonomy ID not included in committed data.
- Remember row selection based on Entrez ID and Cell Type columns. 
- Include Taxonomy ID attribute in committed data.
> [FIX] Marker genes row selection and tax ID attribute

- orangecontrib/single_cell/preprocess/alignment.py
- orangecontrib/single_cell/preprocess/biweight.py
- orangecontrib/single_cell/tests/preprocess/test_alignment.py
- requirements.txt
Fixes #295 
Copied code from `astropy` into scOrange (biweights midcorrelation and dependent methods). Remove `astropy` dependency.
> Remove astropy dependency

- orangecontrib/single_cell/widgets/contingency_table.py
- orangecontrib/single_cell/widgets/owdotmatrix.py
Fixes #294 
Added checks for missing data. This should fix the errors when there is no data on input.
> [FIX] OWDotMatrix: Fixed errors on settings change with no data.

- orangecontrib/single_cell/tests/test_owtsne.py
- orangecontrib/single_cell/widgets/owtsne.py
Continuation of https://github.com/biolab/orange3/pull/3260.
> OWtSNE: Reorganize projections

- orangecontrib/single_cell/widgets/owdotmatrix.py
Fixes #302 
Added a togglable option that normalizes the data.
> [ENH] OWDotMatrix: Added normalization

- orangecontrib/single_cell/widgets/owscorecells.py
Don't commit data if organisms from input genes and markers genes do not match.
> [FIX]OWScoreCells: properly handle new signals

- orangecontrib/single_cell/widgets/owscorecells.py
- do not output None when data exists
- check input genes before creating output data
> [FIX] ScoreCells: Do not output None

- orangecontrib/single_cell/tests/test_owloaddata.py
- orangecontrib/single_cell/widgets/load_data.py
Fix a bug made in #331
- consider series data type when guessing variable type
- fix OWLoadData widget tests
> [FIX] Loader: Consider series data type when guessing variables

- orangecontrib/single_cell/launcher/config.py
- orangecontrib/single_cell/launcher/welcome.py
> launcher: open link insted of example workflow on welcome page

- orangecontrib/single_cell/tests/test_owscorecells.py
- orangecontrib/single_cell/widgets/owscorecells.py
> [ENH] owscorecells: output the data even if no gene markers are provided

- orangecontrib/single_cell/preprocess/scpreprocess.py
- orangecontrib/single_cell/tests/preprocess/test_scpreprocess.py
- orangecontrib/single_cell/tests/test_owscpreprocess.py
- orangecontrib/single_cell/widgets/icons/Dropout.svg
- orangecontrib/single_cell/widgets/owscpreprocess.py
Implements preprocessing part of #348
> [ENH] Preprocess: Add dropout-based gene selection

- orangecontrib/single_cell/tests/test_owdotmatrix.py
- orangecontrib/single_cell/widgets/owdotmatrix.py
Widget had bad columns/rows ordering and several other bugs. 
Some changes made to the widget:
- Hierarchical clustering used for sorting columns/rows
- Input information moved to the bottom widget bar
- Sorting is made after normalization
- Some functionalities moved to other functions (in some menu option cases it led to less computing)
- Outputs are removed when no input data
- Errors and warnings restructured to use new interface
- New unit tests
- Few other minor fixes
I will add the documentation when we agree with the widget
> [FIX] OWdotMatrix: handle ordering and several other bugs

- orangecontrib/single_cell/preprocess/scpreprocess.py
- orangecontrib/single_cell/tests/test_owdropout.py
- orangecontrib/single_cell/widgets/icons/Dropout.svg
- orangecontrib/single_cell/widgets/owdropout.py
> [ENH] Dropout Genes Selection: New widget

- orangecontrib/single_cell/widgets/owdotmatrix.py
With new release Msg import starts to fail
It is fixed now
> Fix Msg import

- orangecontrib/single_cell/launcher/__init__.py
- orangecontrib/single_cell/launcher/welcome.py
Account for split canvas (https://github.com/biolab/orange3/pull/3772)
Update the launcher.
> [FIX] Refactor launcher to account for split canvas

- README.md
Add Discord channel badge and convert all the rest to markdown - it is probably easier to maintain it.
> Add Discord badge and convert to markdown

- orangecontrib/single_cell/tests/test_owmultisample.py
> [FIX] Multi Sample: Fix test_settings

- orangecontrib/single_cell/__main__.py
> Remove __main__ which try to import unexacting module

- orangecontrib/single_cell/widgets/owfilter.py
- orangecontrib/single_cell/widgets/owscoregenes.py
Some widgets are not compatible with PyQt6
Minor fixes for PyQt compatibility.
**Note: This PR should be merged after #392**
> [FIX] Make widget PyQt6 compatible

- orangecontrib/single_cell/widgets/owscdatasets.py
> [FIX] datasets: pass taxonomy id as string not int
